# Important Notes:
# Every field you add must be added to the root build.gradle expandProps map.

# Project
version=1.0.0
group=de.keksuccino.konkrete

# Mod
mod_name=Konkrete
mod_id=konkrete
mod_version=1.9.10
mod_description=Library for Keksuccino's mods.
mod_license=Apache-2.0
mod_authors=Keksuccino

# Common
minecraft_version=1.21.4

# Fabric
fabric_version=0.111.0+1.21.4
fabric_short_version=0.111.0
fabric_loader_version=0.16.9

# Forge
forge_version=54.0.6
forge_loader_version=54

# NeoForge
neoforge_version=21.4.12-beta
neoforge_loader_version=2

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
