package de.keksuccino.konkrete.placeholder.placeholders;

import com.google.gson.JsonObject;
import com.google.gson.JsonParser;
import org.junit.jupiter.api.Test;

import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.Reader;
import java.nio.charset.StandardCharsets;
import java.util.Set;
import java.util.TreeSet;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

class BuiltinPlaceholderLocalizationTest {

    private static final Set<String> EXPECTED_LOCALES = Set.of("de_de.json", "el_gr.json", "en_us.json", "es_mx.json", "fr_fr.json", "ja_jp.json", "ko_kr.json", "pl_pl.json", "ru_ru.json", "zh_cn.json");
    // This explicit contract covers every default and opt-in entry owned by BuiltinPlaceholders, including inherited world descriptions.
    private static final Set<String> RETAINED_BUILTIN_METADATA_KEYS = Set.of(
            "konkrete.placeholders.absolute_number",
            "konkrete.placeholders.absolute_number.desc",
            "konkrete.placeholders.absolute_path",
            "konkrete.placeholders.absolute_path.desc",
            "konkrete.placeholders.alternating_case_text",
            "konkrete.placeholders.alternating_case_text.desc",
            "konkrete.placeholders.base64_decode",
            "konkrete.placeholders.base64_decode.desc",
            "konkrete.placeholders.base64_encode",
            "konkrete.placeholders.base64_encode.desc",
            "konkrete.placeholders.calc",
            "konkrete.placeholders.calc.desc",
            "konkrete.placeholders.categories.world",
            "konkrete.placeholders.clicks_per_second",
            "konkrete.placeholders.clicks_per_second.desc",
            "konkrete.placeholders.clipboard_content",
            "konkrete.placeholders.clipboard_content.desc",
            "konkrete.placeholders.cpu_info",
            "konkrete.placeholders.cpu_info.desc",
            "konkrete.placeholders.crop_text",
            "konkrete.placeholders.crop_text.desc",
            "konkrete.placeholders.file_md5",
            "konkrete.placeholders.file_md5.desc",
            "konkrete.placeholders.file_size",
            "konkrete.placeholders.file_size.desc",
            "konkrete.placeholders.file_text",
            "konkrete.placeholders.file_text.desc",
            "konkrete.placeholders.fps",
            "konkrete.placeholders.fps.desc",
            "konkrete.placeholders.gpu_info",
            "konkrete.placeholders.gpu_info.desc",
            "konkrete.placeholders.guiheight",
            "konkrete.placeholders.guiheight.desc",
            "konkrete.placeholders.guiscale",
            "konkrete.placeholders.guiscale.desc",
            "konkrete.placeholders.guiwidth",
            "konkrete.placeholders.guiwidth.desc",
            "konkrete.placeholders.java_version",
            "konkrete.placeholders.java_version.desc",
            "konkrete.placeholders.json",
            "konkrete.placeholders.json.desc",
            "konkrete.placeholders.jvm_cpu_usage",
            "konkrete.placeholders.jvm_cpu_usage.desc",
            "konkrete.placeholders.jvm_name",
            "konkrete.placeholders.jvm_name.desc",
            "konkrete.placeholders.kebab_case_text",
            "konkrete.placeholders.kebab_case_text.desc",
            "konkrete.placeholders.last_death_message",
            "konkrete.placeholders.last_death_message.desc",
            "konkrete.placeholders.last_world_server",
            "konkrete.placeholders.last_world_server.desc",
            "konkrete.placeholders.loaded_mods",
            "konkrete.placeholders.loaded_mods.desc",
            "konkrete.placeholders.loader_name",
            "konkrete.placeholders.loader_name.desc",
            "konkrete.placeholders.loader_version",
            "konkrete.placeholders.loader_version.desc",
            "konkrete.placeholders.local",
            "konkrete.placeholders.local.desc",
            "konkrete.placeholders.lowercase_text",
            "konkrete.placeholders.lowercase_text.desc",
            "konkrete.placeholders.math_ceil",
            "konkrete.placeholders.math_ceil.desc",
            "konkrete.placeholders.math_cos",
            "konkrete.placeholders.math_cos.desc",
            "konkrete.placeholders.math_cosh",
            "konkrete.placeholders.math_cosh.desc",
            "konkrete.placeholders.math_floor",
            "konkrete.placeholders.math_floor.desc",
            "konkrete.placeholders.math_round",
            "konkrete.placeholders.math_round.desc",
            "konkrete.placeholders.math_sign",
            "konkrete.placeholders.math_sign.desc",
            "konkrete.placeholders.math_sin",
            "konkrete.placeholders.math_sin.desc",
            "konkrete.placeholders.math_sinh",
            "konkrete.placeholders.math_sinh.desc",
            "konkrete.placeholders.math_tan",
            "konkrete.placeholders.math_tan.desc",
            "konkrete.placeholders.math_tanh",
            "konkrete.placeholders.math_tanh.desc",
            "konkrete.placeholders.max_number",
            "konkrete.placeholders.max_number.desc",
            "konkrete.placeholders.maxram",
            "konkrete.placeholders.mcversion",
            "konkrete.placeholders.mcversion.desc",
            "konkrete.placeholders.min_number",
            "konkrete.placeholders.min_number.desc",
            "konkrete.placeholders.minecraft_option_value",
            "konkrete.placeholders.minecraft_option_value.desc",
            "konkrete.placeholders.modversion",
            "konkrete.placeholders.modversion.desc",
            "konkrete.placeholders.mouseposx",
            "konkrete.placeholders.mouseposx.desc",
            "konkrete.placeholders.mouseposy",
            "konkrete.placeholders.mouseposy.desc",
            "konkrete.placeholders.nbt_data_get.client",
            "konkrete.placeholders.nbt_data_get.client.desc",
            "konkrete.placeholders.nbt_data_get.server",
            "konkrete.placeholders.nbt_data_get.server.desc",
            "konkrete.placeholders.negate_number",
            "konkrete.placeholders.negate_number.desc",
            "konkrete.placeholders.number_base_convert",
            "konkrete.placeholders.number_base_convert.desc",
            "konkrete.placeholders.opengl_version",
            "konkrete.placeholders.opengl_version.desc",
            "konkrete.placeholders.os",
            "konkrete.placeholders.os.desc",
            "konkrete.placeholders.os_cpu_usage",
            "konkrete.placeholders.os_cpu_usage.desc",
            "konkrete.placeholders.percentram",
            "konkrete.placeholders.pi",
            "konkrete.placeholders.pi.desc",
            "konkrete.placeholders.playername",
            "konkrete.placeholders.playername.desc",
            "konkrete.placeholders.playeruuid",
            "konkrete.placeholders.playeruuid.desc",
            "konkrete.placeholders.random_number",
            "konkrete.placeholders.random_number.desc",
            "konkrete.placeholders.randomtext",
            "konkrete.placeholders.randomtext.desc",
            "konkrete.placeholders.realtime_day",
            "konkrete.placeholders.realtime_hour",
            "konkrete.placeholders.realtime_hour.desc",
            "konkrete.placeholders.realtime_minute",
            "konkrete.placeholders.realtime_month",
            "konkrete.placeholders.realtime_second",
            "konkrete.placeholders.realtime_year",
            "konkrete.placeholders.replace_text",
            "konkrete.placeholders.replace_text.desc",
            "konkrete.placeholders.screen_identifier",
            "konkrete.placeholders.screen_identifier.desc",
            "konkrete.placeholders.sentence_case_text",
            "konkrete.placeholders.sentence_case_text.desc",
            "konkrete.placeholders.servermotd",
            "konkrete.placeholders.servermotd.desc",
            "konkrete.placeholders.serverping",
            "konkrete.placeholders.serverping.desc",
            "konkrete.placeholders.serverplayercount",
            "konkrete.placeholders.serverplayercount.desc",
            "konkrete.placeholders.serverstatus",
            "konkrete.placeholders.serverstatus.desc",
            "konkrete.placeholders.serverversion",
            "konkrete.placeholders.serverversion.desc",
            "konkrete.placeholders.snake_case_text",
            "konkrete.placeholders.snake_case_text.desc",
            "konkrete.placeholders.split_text",
            "konkrete.placeholders.split_text.desc",
            "konkrete.placeholders.stringify",
            "konkrete.placeholders.stringify.desc",
            "konkrete.placeholders.switch_case",
            "konkrete.placeholders.switch_case.desc",
            "konkrete.placeholders.text_char_count",
            "konkrete.placeholders.text_char_count.desc",
            "konkrete.placeholders.text_width",
            "konkrete.placeholders.text_width.desc",
            "konkrete.placeholders.title_case_text",
            "konkrete.placeholders.title_case_text.desc",
            "konkrete.placeholders.toggle_case_text",
            "konkrete.placeholders.toggle_case_text.desc",
            "konkrete.placeholders.totalmods",
            "konkrete.placeholders.totalmods.desc",
            "konkrete.placeholders.trim_text",
            "konkrete.placeholders.trim_text.desc",
            "konkrete.placeholders.unix_time",
            "konkrete.placeholders.uppercase_text",
            "konkrete.placeholders.uppercase_text.desc",
            "konkrete.placeholders.uptime_seconds",
            "konkrete.placeholders.uptime_seconds.desc",
            "konkrete.placeholders.usedram",
            "konkrete.placeholders.webtext",
            "konkrete.placeholders.webtext.desc",
            "konkrete.placeholders.world.action_bar_message",
            "konkrete.placeholders.world.action_bar_message.desc",
            "konkrete.placeholders.world.action_bar_message_time",
            "konkrete.placeholders.world.action_bar_message_time.desc",
            "konkrete.placeholders.world.active_effect",
            "konkrete.placeholders.world.active_effect.desc",
            "konkrete.placeholders.world.active_hotbar_slot",
            "konkrete.placeholders.world.active_hotbar_slot.desc",
            "konkrete.placeholders.world.boss_count",
            "konkrete.placeholders.world.boss_count.desc",
            "konkrete.placeholders.world.boss_name",
            "konkrete.placeholders.world.boss_name.desc",
            "konkrete.placeholders.world.camera_rotation_delta_x",
            "konkrete.placeholders.world.camera_rotation_delta_x.desc",
            "konkrete.placeholders.world.camera_rotation_delta_y",
            "konkrete.placeholders.world.camera_rotation_delta_y.desc",
            "konkrete.placeholders.world.camera_rotation_x",
            "konkrete.placeholders.world.camera_rotation_x.desc",
            "konkrete.placeholders.world.camera_rotation_y",
            "konkrete.placeholders.world.camera_rotation_y.desc",
            "konkrete.placeholders.world.current_biome",
            "konkrete.placeholders.world.current_biome.desc",
            "konkrete.placeholders.world.current_boss_health",
            "konkrete.placeholders.world.current_boss_health.desc",
            "konkrete.placeholders.world.current_dimension",
            "konkrete.placeholders.world.current_dimension.desc",
            "konkrete.placeholders.world.current_mount_health",
            "konkrete.placeholders.world.current_mount_health.desc",
            "konkrete.placeholders.world.current_mount_health_percent",
            "konkrete.placeholders.world.current_mount_health_percent.desc",
            "konkrete.placeholders.world.current_mount_jump_meter",
            "konkrete.placeholders.world.current_mount_jump_meter.desc",
            "konkrete.placeholders.world.current_player_absorption_health",
            "konkrete.placeholders.world.current_player_absorption_health.desc",
            "konkrete.placeholders.world.current_player_armor",
            "konkrete.placeholders.world.current_player_armor.desc",
            "konkrete.placeholders.world.current_player_armor_percent",
            "konkrete.placeholders.world.current_player_armor_percent.desc",
            "konkrete.placeholders.world.current_player_exp_progress",
            "konkrete.placeholders.world.current_player_exp_progress.desc",
            "konkrete.placeholders.world.current_player_experience",
            "konkrete.placeholders.world.current_player_experience.desc",
            "konkrete.placeholders.world.current_player_health",
            "konkrete.placeholders.world.current_player_health.desc",
            "konkrete.placeholders.world.current_player_health_percent",
            "konkrete.placeholders.world.current_player_health_percent.desc",
            "konkrete.placeholders.world.current_player_hunger",
            "konkrete.placeholders.world.current_player_hunger.desc",
            "konkrete.placeholders.world.current_player_hunger_percent",
            "konkrete.placeholders.world.current_player_hunger_percent.desc",
            "konkrete.placeholders.world.current_player_hunger_saturation",
            "konkrete.placeholders.world.current_player_hunger_saturation.desc",
            "konkrete.placeholders.world.current_player_level",
            "konkrete.placeholders.world.current_player_level.desc",
            "konkrete.placeholders.world.current_player_oxygen",
            "konkrete.placeholders.world.current_player_oxygen.desc",
            "konkrete.placeholders.world.current_player_oxygen_percent",
            "konkrete.placeholders.world.current_player_oxygen_percent.desc",
            "konkrete.placeholders.world.current_server_ip",
            "konkrete.placeholders.world.current_server_ip.desc",
            "konkrete.placeholders.world.current_title",
            "konkrete.placeholders.world.current_title.desc",
            "konkrete.placeholders.world.current_world_seed",
            "konkrete.placeholders.world.current_world_seed.desc",
            "konkrete.placeholders.world.difficulty",
            "konkrete.placeholders.world.difficulty.desc",
            "konkrete.placeholders.world.effects_count",
            "konkrete.placeholders.world.effects_count.desc",
            "konkrete.placeholders.world.gamerule_value",
            "konkrete.placeholders.world.gamerule_value.desc",
            "konkrete.placeholders.world.highlighted_item_time",
            "konkrete.placeholders.world.highlighted_item_time.desc",
            "konkrete.placeholders.world.hovered_inventory_item",
            "konkrete.placeholders.world.hovered_inventory_item.desc",
            "konkrete.placeholders.world.inventory_item_count",
            "konkrete.placeholders.world.inventory_item_count.desc",
            "konkrete.placeholders.world.inventory_slot_food_point_restore_amount",
            "konkrete.placeholders.world.inventory_slot_food_point_restore_amount.desc",
            "konkrete.placeholders.world.item_category",
            "konkrete.placeholders.world.item_category.desc",
            "konkrete.placeholders.world.level_save_data",
            "konkrete.placeholders.world.level_save_data.desc",
            "konkrete.placeholders.world.level_save_names",
            "konkrete.placeholders.world.level_save_names.desc",
            "konkrete.placeholders.world.max_mount_health",
            "konkrete.placeholders.world.max_mount_health.desc",
            "konkrete.placeholders.world.max_player_absorption_health",
            "konkrete.placeholders.world.max_player_absorption_health.desc",
            "konkrete.placeholders.world.max_player_armor",
            "konkrete.placeholders.world.max_player_armor.desc",
            "konkrete.placeholders.world.max_player_health",
            "konkrete.placeholders.world.max_player_health.desc",
            "konkrete.placeholders.world.max_player_hunger",
            "konkrete.placeholders.world.max_player_hunger.desc",
            "konkrete.placeholders.world.max_player_oxygen",
            "konkrete.placeholders.world.max_player_oxygen.desc",
            "konkrete.placeholders.world.player_armor_toughness",
            "konkrete.placeholders.world.player_armor_toughness.desc",
            "konkrete.placeholders.world.player_attack_strength",
            "konkrete.placeholders.world.player_attack_strength.desc",
            "konkrete.placeholders.world.player_gamemode",
            "konkrete.placeholders.world.player_gamemode.desc",
            "konkrete.placeholders.world.player_item_use_progress",
            "konkrete.placeholders.world.player_item_use_progress.desc",
            "konkrete.placeholders.world.player_position_delta_x",
            "konkrete.placeholders.world.player_position_delta_x.desc",
            "konkrete.placeholders.world.player_position_delta_y",
            "konkrete.placeholders.world.player_position_delta_y.desc",
            "konkrete.placeholders.world.player_position_delta_z",
            "konkrete.placeholders.world.player_position_delta_z.desc",
            "konkrete.placeholders.world.player_view_direction",
            "konkrete.placeholders.world.player_view_direction.desc",
            "konkrete.placeholders.world.player_x_coordinate",
            "konkrete.placeholders.world.player_x_coordinate.desc",
            "konkrete.placeholders.world.player_y_coordinate",
            "konkrete.placeholders.world.player_y_coordinate.desc",
            "konkrete.placeholders.world.player_z_coordinate",
            "konkrete.placeholders.world.player_z_coordinate.desc",
            "konkrete.placeholders.world.players_list",
            "konkrete.placeholders.world.players_list.desc",
            "konkrete.placeholders.world.slot_item",
            "konkrete.placeholders.world.slot_item.desc",
            "konkrete.placeholders.world.slot_item_count",
            "konkrete.placeholders.world.slot_item_count.desc",
            "konkrete.placeholders.world.slot_item_display_name",
            "konkrete.placeholders.world.slot_item_display_name.desc",
            "konkrete.placeholders.world.slot_item_durability",
            "konkrete.placeholders.world.slot_item_durability.desc",
            "konkrete.placeholders.world.world_day_time",
            "konkrete.placeholders.world.world_day_time.desc",
            "konkrete.placeholders.world.world_day_time_hour",
            "konkrete.placeholders.world.world_day_time_hour.desc",
            "konkrete.placeholders.world.world_day_time_minute",
            "konkrete.placeholders.world.world_day_time_minute.desc",
            "konkrete.placeholders.world.world_game_time",
            "konkrete.placeholders.world.world_game_time.desc",
            "konkrete.placeholders.world_load_progress",
            "konkrete.placeholders.world_load_progress.desc",
            "konkrete.requirements.categories.advanced",
            "konkrete.requirements.categories.client",
            "konkrete.requirements.categories.gui",
            "konkrete.requirements.categories.other",
            "konkrete.requirements.categories.player",
            "konkrete.requirements.categories.realtime",
            "konkrete.requirements.categories.server"
    );

    @Test
    void everyLocaleContainsEveryRetainedBuiltinMetadataKey() throws IOException {
        int managedBuiltins = BuiltinPlaceholders.all().size() + BuiltinPlaceholders.recentDestinationBacked().size();
        assertEquals(160, managedBuiltins, "Update the explicit localization contract when built-in coverage changes");

        for (String locale : EXPECTED_LOCALES) {
            JsonObject translations;
            InputStream input = BuiltinPlaceholderLocalizationTest.class.getResourceAsStream("/assets/konkrete/lang/" + locale);
            assertNotNull(input, () -> "Missing packaged locale: " + locale);
            try (Reader reader = new InputStreamReader(input, StandardCharsets.UTF_8)) {
                translations = JsonParser.parseReader(reader).getAsJsonObject();
            }
            Set<String> missing = new TreeSet<>(RETAINED_BUILTIN_METADATA_KEYS);
            missing.removeAll(translations.keySet());
            assertTrue(missing.isEmpty(), () -> locale + " is missing retained placeholder metadata keys: " + missing);
        }
    }
}
