
plugins {
    id 'idea'
    id 'maven-publish'
    id "net.neoforged.gradle.userdev" version "$neogradle_version"
    id 'java-library'
    id "com.gradleup.shadow"
}

base {
    archivesName = "${mod_id}"
}

configurations {
    shadow
    implementation.extendsFrom(shadow)
}

// Automatically enable neoforge AccessTransformers if the file exists
// This location is hardcoded in FML and can not be changed.
// https://github.com/neoforged/FancyModLoader/blob/a952595eaaddd571fbc53f43847680b00894e0c1/loader/src/main/java/net/neoforged/fml/loading/moddiscovery/ModFile.java#L118
if (file('src/main/resources/META-INF/accesstransformer.cfg').exists()) {
    minecraft.accessTransformers.file file('src/main/resources/META-INF/accesstransformer.cfg')
}

runs {
    configureEach {
        modSource project.sourceSets.main
    }
    client {
        workingDirectory project.file('../run_client')
        systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
    }
    server {
        workingDirectory project.file('../run_server')
        systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        arguments.add('--nogui')
    }
}

tasks.withType(JavaExec).configureEach {
    if (name == "runClient" || name == "runServer") {
        standardInput = System.in
    }
}

//Temporarily disabled tests so compiling doesn't fail until I figure out why tf neoforge:test fails
test {
    exclude '**/*'
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

//subsystems {
//    parchment {
//        minecraftVersion = "${parchment_mc_version}"
//        mappingsVersion = "${parchment_version}"
//    }
//}

dependencies {
    testImplementation("org.junit.jupiter:junit-jupiter-api:5.10.2")
    testRuntimeOnly("org.junit.jupiter:junit-jupiter-engine:5.10.2")
    implementation "net.neoforged:neoforge:${neoforge_version}"
    shadow "net.objecthunter:exp4j:0.4.8"
    shadow("com.jayway.jsonpath:json-path:2.9.0") {
        exclude group: "org.slf4j", module: "slf4j-api"
    }
    //    shadow "com.github.DhyanB:Open-Imaging:317b2cb6e5"
    shadow("net.minidev:json-smart:2.6.0") {
        exclude group: "org.ow2.asm", module: "asm"
    }
    compileOnly project(":common")
}

// Exclude Fabric Loader from NeoForge
configurations {
    runtimeClasspath    { exclude group: 'net.fabricmc', module: 'fabric-loader' }
    developmentRuntimeClasspath {
        // Gradle 8 names used by ForgeGradle 6
        exclude group: 'net.fabricmc', module: 'fabric-loader'
    }
}

// Exclude Fabric Loader from NeoForge
configurations {
    runtimeClasspath    { exclude group: 'net.fabricmc', module: 'fabric-loader' }
    developmentRuntimeClasspath {
        // Gradle 8 names used by ForgeGradle 6
        exclude group: 'net.fabricmc', module: 'fabric-loader'
    }
}

// NeoGradle compiles the game, but we don't want to add our common code to the game's code++
Spec<Task> notNeoTask = { Task it -> !it.name.startsWith("neo") } as Spec<Task>

tasks.named("compileJava", JavaCompile).configure {
    source(project(":common").sourceSets.main.allSource)
}

tasks.named("jar") {
    archiveClassifier.set("unshaded")
}

tasks.named("shadowJar") {
    archiveClassifier.set("")
    configurations = [project.configurations.shadow]
    mergeServiceFiles()
    exclude 'org/slf4j/**'
    exclude 'org/objectweb/asm/**'
    relocate 'com.jayway.jsonpath', 'de.keksuccino.com.jayway.jsonpath'
    relocate 'net.minidev', 'de.keksuccino.net.minidev'
    relocate 'net.objecthunter.exp4j', 'de.keksuccino.net.objecthunter.exp4j'
}

tasks.named("assemble") {
    dependsOn tasks.shadowJar
}

tasks.withType(JavaCompile).matching(notNeoTask).configureEach {
    it.options.compilerArgs += ['-Xlint:-deprecation', '-Xlint:-removal']
}

tasks.withType(Javadoc).matching(notNeoTask).configureEach {
    source(project(":common").sourceSets.main.allJava)
}

tasks.named("sourcesJar", Jar) {
    from(project(":common").sourceSets.main.allSource)
}

tasks.withType(ProcessResources).matching(notNeoTask).configureEach {
    from project(":common").sourceSets.main.resources
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            artifactId base.archivesName.get()
            artifact tasks.shadowJar
            artifact tasks.sourcesJar
        }
    }
    repositories {
        maven {
            url "file://" + System.getenv("local_maven")
        }
    }
}
